version: "3.3"

networks:
  proxy:
    external: true

services:

  jupyter: # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html
    image: jupyter/tensorflow-notebook
    container_name: jupyter
    networks:
      - proxy
    command: ["start-notebook.sh", "--NotebookApp.password=${JUPYTER_TOKEN}"]
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - RESTARTABLE=yes
    restart: unless-stopped
    user: root
    volumes:
      - ${DATA_DIR}/jupyter:/home/jovyan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.entrypoints=http"
      - "traefik.http.routers.jupyter.rule=Host(`jupyter.${DOMAIN}`)"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
      - "traefik.http.middlewares.jupyter.errors.status=400-599"
      - "traefik.http.middlewares.jupyter.errors.service=organizr@docker"
      - "traefik.http.middlewares.jupyter.errors.query=/?error={status}.html&return=jupyter.${DOMAIN}"
      - "traefik.http.routers.jupyter.middlewares=auth"
      - "traefik.http.middlewares.auth.forwardauth.address=http://organizr/api/?v1/auth&group=0"

